{{- if .Values.store.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.store.name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.store.name }}
      app.kubernetes.io/component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.store.name }}
        app.kubernetes.io/component: mysql
    spec:
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.store.name }}-mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.store.name }}-mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.store.name }}-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.store.name }}-mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        {{- if .Values.mysql.livenessProbe.enabled }}
        livenessProbe:
          exec:
            {{- toYaml .Values.mysql.livenessProbe.exec | nindent 12 }}
          initialDelaySeconds: {{ .Values.mysql.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.mysql.readinessProbe.enabled }}
        readinessProbe:
          exec:
            {{- toYaml .Values.mysql.readinessProbe.exec | nindent 12 }}
          initialDelaySeconds: {{ .Values.mysql.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.mysql.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.mysql.readinessProbe.timeoutSeconds }}
        {{- end }}
        resources:
          {{- toYaml .Values.mysql.resources | nindent 10 }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        {{- if .Values.mysql.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.store.name }}-mysql-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}